### ISSUE TITLE
Crashes on MS SQL Server

### ISSUE THREAD

**Issue by me21** [manuelvillar/sequelize-auto-migrations-ng#15]
It is caused by https://github.com/sequelize/sequelize/issues/8761. I don't know what should be done - waiting for sequelize to fix that, changing your project to avoid JSON data type usage, etc. But let it be here so this information can be found in advance.

The error is: 

```
{ SequelizeDatabaseError: Column, parameter, or variable #3: Cannot find data type JSON.
    at Query.formatError (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request._this.callback (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\request.js:60:27)
    at Connection.endOfMessageMarkerReceived (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\connection.js:1922:20)
    at Connection.dispatchEvent (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\connection.js:1004:38)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\connection.js:805:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at Parser.afterTransform (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:91:10)
    at Parser._transform (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:69:9)
    at Parser.Transform._read (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Parser.Transform._write (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Parser.Writable.write (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_writable.js:334:11)
  name: 'SequelizeDatabaseError',
  parent: 
   { RequestError: Column, parameter, or variable #3: Cannot find data type JSON.
    at RequestError (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\errors.js:34:12)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\connection.js:614:36)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at doneParsing (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:110:18)
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:46:5
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:247:9
    at Parser.awaitData (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:144:9)
    at Parser.readUInt32LE (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:244:12)
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:12:90
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:446:11
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:433:9
    at Parser.awaitData (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:144:9)
    at Parser.readBuffer (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:430:12)
     message: 'Column, parameter, or variable #3: Cannot find data type JSON.',
     code: 'EREQUEST',
     number: 2715,
     state: 6,
     class: 16,
     serverName: 'ZARUBKIN-NOTE',
     procName: '',
     lineNumber: 1,
     sql: 'IF OBJECT_ID(\'[SequelizeMetaMigrations]\', \'U\') IS NULL CREATE TABLE [SequelizeMetaMigrations] ([revision] INTEGER NOT NULL UNIQUE , [name] NVARCHAR(255) NOT NULL, [state] JSON NOT NULL, PRIMARY KEY ([revision]));' },
  original: 
   { RequestError: Column, parameter, or variable #3: Cannot find data type JSON.
    at RequestError (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\errors.js:34:12)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\connection.js:614:36)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at doneParsing (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:110:18)
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:46:5
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:247:9
    at Parser.awaitData (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:144:9)
    at Parser.readUInt32LE (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:244:12)
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\infoerror-token-parser.js:12:90
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:446:11
    at C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:433:9
    at Parser.awaitData (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:144:9)
    at Parser.readBuffer (C:\Users\Зарубкин\Documents\React Projects\uno\backend\node_modules\tedious\lib\token\stream-parser.js:430:12)
     message: 'Column, parameter, or variable #3: Cannot find data type JSON.',
     code: 'EREQUEST',
     number: 2715,
     state: 6,
     class: 16,
     serverName: 'ZARUBKIN-NOTE',
     procName: '',
     lineNumber: 1,
     sql: 'IF OBJECT_ID(\'[SequelizeMetaMigrations]\', \'U\') IS NULL CREATE TABLE [SequelizeMetaMigrations] ([revision] INTEGER NOT NULL UNIQUE , [name] NVARCHAR(255) NOT NULL, [state] JSON NOT NULL, PRIMARY KEY ([revision]));' },
  sql: 'IF OBJECT_ID(\'[SequelizeMetaMigrations]\', \'U\') IS NULL CREATE TABLE [SequelizeMetaMigrations] ([revision] INTEGER NOT NULL UNIQUE , [name] NVARCHAR(255) NOT NULL, [state] JSON NOT NULL, PRIMARY KEY ([revision]));' }

```

**Comment by mccabemj** [comment]
@me21 There is no support for a JSON data type in MSSQL (unless its been added since I last checked)

The issue you are referring to did not cause this. The support isn't even in the base DB engine. MSSQL provides helpers but the underlying data type is still a string
